name: haarcascade
description: "A new Flutter package project."
version: 0.0.1
repository: "https://github.com/danemadsen/flutter_haarcascade"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  opencv_dart: ^1.3.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/haarcascade_frontalface_default.xml
